### PR TITLE
Update code to use 'Expose input' Formless PR

### PR DESCRIPTION
**Pull request by JordanMartinez**
I'm temporarily using my branch of Formless. Once my PR gets merged and all discussion is finished, we only need to update the 'packages.dhall' file to use your Formless repo's release tag that includes that code.

### CODE REVIEW

**Review by thomashoneyman — APPROVED** [review]
I'm marking this approved, but I'd like to wait to merge until this can point back to the official formless branch so I don't forget :) Once that's merged, I'll drop a comment here to let you know the dependency ought to be updated.

**Comment by JordanMartinez** [comment]
Sounds good!

**Comment by thomashoneyman** [comment]
Merged!

**Comment by JordanMartinez** [comment]
Ok. It's pointing back at your Formless PR

**Comment by thomashoneyman** [comment]
Thanks!

**Pull request merged**
