### PR TITLE
upgrade to parcel2

### PR DESCRIPTION
**Pull request by wryk**
[Parcel v2.0.0 stable](https://parceljs.org/blog/v2/) has been announced by the Parcel team the 13/10/2021.

This MR upgrade the dependency accordingly and some others parts to use the newest features :
* Configure [html entry file from `packages.json#source`](https://parceljs.org/getting-started/webapp/#package-scripts) rather than in the commands
* Use [Development branch removal](https://parceljs.org/features/production/#development-branch-removal) in `index.js` instead of the duplicated dev-only html entry for conditional DCE code loading

I removed `.cache` folder from the clean script because Parcel uses `.parcel-cache` but I didn't removed it from `.gitignore` to not pollute other users' repositories.

*Note: I manually [aliased `xhr2` to an empty module](https://parceljs.org/features/dependency-resolution/#shim-aliases) for the browser target because Parcel tried hard to bundle it and we really don't want that : `@parcel/core: Failed to resolve 'xhr2' from './output/Affjax/foreign.js'`*

### CODE REVIEW

**Review by thomashoneyman — APPROVED** [review]

**Comment by wryk** [comment]
Oh gosh I dunno how but I missed this PR somehow broke the production build, I'm on it rn

**Comment by wryk** [comment]
This is an issue with Parcel transforming `typeof module !== "undefined"` to `"object" !== "undefined"` at https://github.com/purescript-contrib/purescript-affjax/blob/v12.0.0/src/Affjax.js#L7 and thus breaking the foreign code condition.

This is pretty unexpected and I'll need more time to inspect this and maybe fill out a bug report on Parcel itself.

In the meantime, @thomashoneyman, I will understand if you want to revert this MR

**Comment by thomashoneyman** [comment]
Done: 1df2bfdc852063f59e599c87a05066f71e67c646.

This is unexpected 😬. I haven't been loving my experiences with Parcel 2 so far, and I'm interested in switching to esbuild for this project going forward -- it's a pretty simple build here.

**Comment by wryk** [comment]
esbuild don't ship a dev server and others neat utilities but it makes sense on production build because only a little subset of available features is used.

If my issue on Parcel repository leads to nothing I'm interested to tackle the migration to raw esbuild or a more feature complete build tool using it (I only know [snowpack](https://www.snowpack.dev/guides/optimize-and-bundle) but there may be others)

**Comment by thomashoneyman** [comment]
Yea, I'm not sure about the suite of utilities it provides in general, but I believe it does have a way to run a dev server:
https://esbuild.github.io/api/#serve

**Pull request merged**
